const data = {
    products:[
        {
            _id:'1',
            name:'nome',
            category:'Shirts',
            image:'/img/danceofthebaphomet-mock-flowymuscle.jpg',
            price: 30,
            countInStock: 20,
            brand:'Black Craft',
            rating: 2.5,
            numReviews: 10,
            description:'high quality product',
            alternativeImage: '/img/BC114_098f6b74-6702-4051-929f-d61b61292aac.jpg',
            gender:'man',
        },
        {
            _id:'2',
            name:'nodasdasdme',
            category:'Shirts',
            image: '/img/BCC_Feb2021_229.jpg',
            price: 30,
            countInStock: 10,
            brand:'Black Craft',
            rating: 3.5,
            numReviews: 10,
            description:'high quality product',
            alternativeImage: '/img/BCC_Feb2021_112.jpg',
            gender:'man',
        },
        {
            _id:'3',
            name:'nomdasdasdae',
            category:'Shirts',
            image:'/img/BCC_Oct302021_Braxton_80.jpg',
            price: 30,
            countInStock: 0,
            brand:'Black Craft',
            rating: 3,
            numReviews: 10,
            description:'high quality product',
            alternativeImage: '/img/lucifersdream-pullover-mock.jpg',
            gender:'man',
        },
        {
            _id:'4',
            name:'nomdasdasdae',
            category:'Shirts',
            image:'/img/BCC_Feb2021_378.jpg',
            price: 30,
            brand:'Black Craft',
            rating: 4,
            numReviews: 10,
            description:'high quality product',
            alternativeImage: '/img/BCC_Feb2021_380.jpg',
            gender:'man',
        },
        {
            _id:'5',
            name:'nomeddasdas',
            category:'Shirts',
            image:'/img/CovenMB-Flowy-crop-mock3.jpg',
            price: 30,
            brand:'Black Craft',
            rating: 4.6,
            numReviews: 30,
            description:'high quality product',
            alternativeImage: '/img/CovenMB-Flowy-crop-mock.jpg',
            gender:'man',
        },
        {
            _id:'6',
            name:'nomdasdase',
            category:'Shirts',
            image:'/img/Deadmau5-GoatlordTee3.jpg',
            price: 30,
            brand:'Black Craft',
            rating: 5,
            numReviews: 120,
            description:'high quality product',
            alternativeImage: '/img/Deadmau5-GoatlordTee-2.jpg',
            gender:'man',
        },
        {
            _id:'7',
            name:'nomdasdase',
            category:'Shirts',
            image:'/img/BCC_Sept19_11.jpg',
            price: 30,
            brand:'Black Craft',
            rating: 5,
            numReviews: 120,
            description:'high quality product',
            alternativeImage: '/img/BCC_Sept19_13.jpg',
            gender:'man',
        },
        {
            _id:'8',
            name:'nomdasdase',
            category:'Shirts',
            image:'/img/BC134_e1e94b75-87fd-40fd-b0f7-16fb65b675dc.jpg',
            price: 30,
            brand:'Black Craft',
            rating: 5,
            numReviews: 120,
            description:'high quality product',
            alternativeImage: '/img/BC135_3db8c6f4-2848-4bc5-a358-e45aba3741e6.jpg',
            gender:'man',
        },
        {
            _id:'9',
            name:'nomdasdase',
            category:'Shirts',
            image:'/img/redbaph_buttondown_mock2.jpg',
            price: 30,
            brand:'Black Craft',
            rating: 5,
            numReviews: 120,
            description:'high quality product',
            alternativeImage: '/img/redbaph_buttondown_mock1.jpg',
            gender:'man',
        },
        {
            _id:'10',
            name:'nomdasdase',
            category:'Shirts',
            image:'/img/BCC_Oct302021_Braxton_101.jpg',
            price: 30,
            brand:'Black Craft',
            rating: 5,
            numReviews: 120,
            description:'high quality product',
            alternativeImage: '/img/IMG_3558.jpg',
            gender:'man',
        },
        {
            _id:'11',
            name:'nomdasdase',
            category:'Shirts',
            image:'/img/BCC_Oct19th2021_32.jpg',
            price: 30,
            brand:'Black Craft',
            rating: 5,
            numReviews: 120,
            description:'high quality product',
            alternativeImage: '/img/Vintagehalloweencat-womens-tee.jpg',
            gender:'man',
        },
        {
            _id:'12',
            name:'nomdasdase',
            category:'Shirts',
            image:'/img/Deadmau5-GoatlordTee3.jpg',
            price: 30,
            brand:'Black Craft',
            rating: 5,
            numReviews: 120,
            description:'high quality product',
            alternativeImage: '/img/Deadmau5-GoatlordTee-2.jpg',
            gender:'man',
        },
    ],
};
export default data;